version: "3"

services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    ports:
      - "9870:9870"
      - "8020:8020"
    environment:
      - CLUSTER_NAME=bigdata
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
    volumes:
      - ./hadoop/dfs/name:/hadoop/dfs/name
    networks:
      - bigdata-net

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode
    depends_on:
      - namenode
    ports:
      - "9864:9864"
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
      - SERVICE_PRECONDITION=namenode:9870
    volumes:
      - ./hadoop/dfs/data:/hadoop/dfs/data
    networks:
      - bigdata-net

  hive-server:
    image: apache/hive:4.0.0
    container_name: hive-server
    depends_on:
      - namenode
      - datanode
    environment:
      SERVICE_NAME: hiveserver2
      CORE_CONF_fs_defaultFS: hdfs://namenode:8020
    ports:
      - "10000:10000"
    networks:
      - bigdata-net

  hbase-region:
    image: harisekhon/hbase
    container_name: hbase-region
    depends_on:
      - hbase-master
    networks:
      - bigdata-net

  beeline:
    image: apache/hive:4.0.0
    container_name: beeline
    entrypoint: /bin/bash
    networks:
      - bigdata-net

networks:
  bigdata-net:
    driver: bridge